### ISSUE TITLE
Not working with stable release

### ISSUE THREAD

**Issue by WebShapedBiz** [filipac/oc-themepreview-plugin#1]
It was one of the most useful plugins but it seems that it does not work with just released stable release. I'm always getting selected front end theme in my CMS pages so I cannot work on the target theme.

**Comment by filipac** [comment]
Looking on it!

**Comment by WebShapedBiz** [comment]
Thanx

**Comment by filipac** [comment]
You can now update to version 1.0.2 in October stable version. This should work.

**Comment by WebShapedBiz** [comment]
Already have. Thank you for your time and effort.

Cheers.
